/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Sew(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sew.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[0, 1, 0]} scale={[0.63, 0.63, 0.39]} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[0, 1, 0]} scale={[0.63, 0.63, 0.39]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sew.gltf')
